name: Build and Publish Docker Image
on:
  push:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hiddenswitch/comfyui
jobs:
  build:
    runs-on: [ self-hosted, Linux, X64, cpu ]
    container: "ubuntu:22.04"
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          image: comfyui